services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=gymDB
      - DB_USER=root
      - DB_PASS=root
      - DB_PORT=3306
      - ENCRYPT_SITE_KEY=6LfhVNIsAAAAAFfqThWFXGTFpXjXvlNlkehx_Zmg
      - ENCRYPT_SECRET_KEY=6LfhVNIsAAAAACw1AVr48XToouQuX4YS9MprWIXR
      - MailTrap_api_key=8614d9e38bcdc1ed5b19cef6847b6cca
      - Admin_user=admin
      - Admin_pass=BullGym@2026
      - Admin_email=arian.shafagh2003@gmail.com
    depends_on:
      - db
    networks:
      - gym-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gymDB
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gym-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  db_data:
